redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/alfonso/bycpsicologia/ads-optimized-website"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/alfonso/bycpsicologia/ads-optimized-website"
command = "echo 'Production build'"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index-ads-optimized.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]